spring.application.name=budgetGarden
spring.datasource.url=jdbc:postgresql://gondola.proxy.rlwy.net:16603/railway
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

logging.level.root=INFO
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

google.authorization-url=https://oauth2.googleapis.com/tokeninfo
google.user-info-url=https://openidconnect.googleapis.com/v1/userinfo