spring.application.name=bugetGarden
spring.datasource.url=jdbc:postgresql://gondola.proxy.rlwy.net:16603/railway
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect